# Generated by Django 5.1.4 on 2025-03-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Garage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=255)),
                ('services', models.TextField(help_text='List the services offered, separated by commas')),
                ('owner_name', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
