# Generated by Django 5.1.4 on 2025-03-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocare', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garage',
            name='date_registered',
        ),
        migrations.AddField(
            model_name='garage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='garage_images/'),
        ),
    ]
